# Generated by Django 3.0.5 on 2020-05-04 06:28

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('agent_id', models.CharField(default='AG-23067-38358', max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='Please make sure you begin with the country code, for example : <b><em>+256</em></b>', max_length=30, unique=True)),
                ('location', models.TextField(blank=True)),
                ('username', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agents',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(default='ST-86560-61376', help_text='Please use the following format, where X is a number: <b><em>ST-XXXXX-XXXXX</em></b>.', max_length=255, primary_key=True, serialize=False, validators=[main.models.validate_store_id])),
                ('full_name', models.CharField(help_text='For example <b><em>Mega Standard Supermarket</em></b>', max_length=255)),
                ('short_name', models.CharField(help_text='For example <b><em>Mega Standard</em></b>', max_length=255, unique=True)),
                ('location', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Stores',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StoreItems',
            fields=[
                ('item_id', models.CharField(default='ITEM-2194-3918-8561', help_text='Please use the following format, where X is a number: <b><em>ITEM-XXXX-XXXX-XXXX</em></b>.', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.FloatField(default=0.0)),
                ('category', models.CharField(default='Not Categorised', max_length=255)),
                ('sub_category', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to=main.models.create_upload)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('key_features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('specifications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Store')),
            ],
            options={
                'verbose_name': 'Items',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(default='ORD-3259-7355-1114', max_length=255, primary_key=True, serialize=False)),
                ('address', models.TextField(help_text='Address to deliver the order to')),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_time', models.DateTimeField(blank=True, help_text='Date and time the order will be delivered')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=main.models.items_default, verbose_name='ItemsInfo'), size=None)),
                ('status', models.CharField(choices=[('DELIVERED', 'Delivered'), ('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed, awaits delivery')], default='PENDING', max_length=15)),
                ('send_email', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('delivery_agent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Agents')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
                'ordering': ['status', 'order_time'],
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(default='CU-27026-50048', max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='Please make sure you begin with the country code, for example : <b><em>+256</em></b>', max_length=30)),
                ('location', models.TextField(blank=True)),
                ('subscription', models.BooleanField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customers',
                'verbose_name_plural': 'Customers',
                'ordering': ['customer_id'],
            },
        ),
    ]
