# Generated by Django 3.0.5 on 2020-05-02 19:25

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Agents'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(default='ST-51833-24653', help_text='Please use the following format, where X is a number: <b><em>ST-XXXXX-XXXXX</em></b>.', max_length=255, unique=True, validators=[main.models.validate_store_id]),
        ),
    ]
