# Generated by Django 3.0.5 on 2020-05-04 08:21

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200504_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customer',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='agents',
            name='agent_id',
            field=models.CharField(default='AG-69019-54110', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.CharField(default='CU-39699-70445', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='ORD-3657-7406-8988', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(default='ST-92684-21359', help_text='Please use the following format, where X is a number: <b><em>ST-XXXXX-XXXXX</em></b>.', max_length=255, primary_key=True, serialize=False, validators=[main.models.validate_store_id]),
        ),
        migrations.AlterField(
            model_name='storeitems',
            name='item_id',
            field=models.CharField(default='ITEM-8407-9205-2792', help_text='Please use the following format, where X is a number: <b><em>ITEM-XXXX-XXXX-XXXX</em></b>.', max_length=255, primary_key=True, serialize=False),
        ),
    ]
