# Generated by Django 3.0.5 on 2020-05-04 08:37

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200504_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery_agent',
        ),
        migrations.AlterField(
            model_name='agents',
            name='agent_id',
            field=models.CharField(default='AG-81747-36424', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.CharField(default='CU-84597-54594', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='ORD-7277-3159-3342', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(default='ST-43908-27035', help_text='Please use the following format, where X is a number: <b><em>ST-XXXXX-XXXXX</em></b>.', max_length=255, primary_key=True, serialize=False, validators=[main.models.validate_store_id]),
        ),
        migrations.AlterField(
            model_name='storeitems',
            name='item_id',
            field=models.CharField(default='ITEM-2767-5522-6576', help_text='Please use the following format, where X is a number: <b><em>ITEM-XXXX-XXXX-XXXX</em></b>.', max_length=255, primary_key=True, serialize=False),
        ),
    ]
