# Generated by Django 3.0.5 on 2020-05-04 08:46

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200504_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_id',
            field=models.CharField(default='AG-75742-80033', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.CharField(default='CU-13745-60733', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='ORD-7552-8341-1049', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(default='ST-19069-42640', help_text='Please use the following format, where X is a number: <b><em>ST-XXXXX-XXXXX</em></b>.', max_length=255, primary_key=True, serialize=False, validators=[main.models.validate_store_id]),
        ),
        migrations.AlterField(
            model_name='storeitems',
            name='item_id',
            field=models.CharField(default='ITEM-3579-2775-8767', help_text='Please use the following format, where X is a number: <b><em>ITEM-XXXX-XXXX-XXXX</em></b>.', max_length=255, primary_key=True, serialize=False),
        ),
    ]
