# Generated by Django 3.0.5 on 2020-05-04 10:46

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200504_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_id',
            field=models.CharField(default='AG-54587-76044', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.CharField(default='CU-61378-39257', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customers',
            name='subscription',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_time',
            field=models.DateTimeField(blank=True, help_text="<b style='color:red''>date and time when the order will be delivered</b>", null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='ORD-3788-8253-1121', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(default='ST-57904-47205', help_text='Please use the following format, where X is a number: <b><em>ST-XXXXX-XXXXX</em></b>.', max_length=255, primary_key=True, serialize=False, validators=[main.models.validate_store_id]),
        ),
        migrations.AlterField(
            model_name='storeitems',
            name='item_id',
            field=models.CharField(default='ITEM-6030-9887-3253', help_text='Please use the following format, where X is a number: <b><em>ITEM-XXXX-XXXX-XXXX</em></b>.', max_length=255, primary_key=True, serialize=False),
        ),
    ]
