# Generated by Django 3.0.5 on 2020-05-04 14:29

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200504_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_id',
            field=models.CharField(default='AG-30742-91529', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.CharField(default='CU-33254-23727', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='ORD-5452-5773-1427', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(default='ST-94706-51991', help_text='Please use the following format, where X is a number: <b><em>ST-XXXXX-XXXXX</em></b>.', max_length=255, primary_key=True, serialize=False, validators=[main.models.validate_store_id]),
        ),
        migrations.AlterField(
            model_name='storeitems',
            name='item_id',
            field=models.CharField(default='ITEM-7667-8544-6706', help_text='Please use the following format, where X is a number: <b><em>ITEM-XXXX-XXXX-XXXX</em></b>.', max_length=255, primary_key=True, serialize=False),
        ),
    ]
